spring:
  datasource:
#    TODO: uncomment and complete below data to connect to database
#    url:
#    username:
#    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
    banner-mode: console
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.springframework.security: DEBUG
